{{- if .Values.memcached.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "memcached") }}-headless
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "memcached") | nindent 4 }}
    prometheus.io/service-monitor: "false"
    {{- with .Values.memcached.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.memcached.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: memcached-client
      port: {{ .Values.memcached.port }}
      targetPort: {{ .Values.memcached.port }}
    {{ if .Values.memcached.metricsEnabled }}
    - name: exporter-http-metrics
      port: 9150
      targetPort: 9150
    {{ end }}
  selector:
    {{- include "mimir.selectorLabels" (dict "ctx" . "component" "memcached") | nindent 4 }}
{{- end -}}
